name: barbearia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4 # ou a versão mais recente
  sqflite_common_ffi: ^2.0.0 # para uso em desktop
  sqflite_common_ffi_web: ^0.4.5+3
  path_provider: ^2.0.14
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  mockito: ^5.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.0.16
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
