// Mocks generated by Mockito 5.4.4 from annotations
// in barbearia/test/servico_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:barbearia/models/servico.dart' as _i4;
import 'package:barbearia/services/servico_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ServicoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockServicoService extends _i1.Mock implements _i2.ServicoService {
  MockServicoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> adicionarServico(_i4.Servico? servico) =>
      (super.noSuchMethod(
        Invocation.method(
          #adicionarServico,
          [servico],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Servico>> getServicos() => (super.noSuchMethod(
        Invocation.method(
          #getServicos,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Servico>>.value(<_i4.Servico>[]),
      ) as _i3.Future<List<_i4.Servico>>);

  @override
  _i3.Future<void> updateServico(_i4.Servico? servico) => (super.noSuchMethod(
        Invocation.method(
          #updateServico,
          [servico],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteServico(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteServico,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
